title: Redux Flute
email: kyle@rentalutions.com
description: Smart front-end data cache manager
baseurl: ""
url: "https://kyleramirez.github.io/redux-flute"
markdown: kramdown
google:
    analytics_ua: UA-63931380-3
cdn_path: https://dl.dropboxusercontent.com/u/8256237/redux-flute
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
sass:
  style: compressed
compress_html:
  ignore:
    envs: [development]
#Check https://github.com/penibelst/jekyll-compress-html for more HTML compression configuration options
